// Generated by Selenium IDE


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;

import java.sql.Driver;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;


public class ConversionktotTest {
  private WebDriver driver;

  public static Stream<Arguments> providedrivers() {
    return Stream.of(
            Arguments.of(new ChromeDriver()),
            Arguments.of(new EdgeDriver())
    );
  }


  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @ParameterizedTest
  @MethodSource("providedrivers")
  public void conversionktot(WebDriver driver) {
    this.driver = driver;
    driver.get("https://www.onlineconversion.com/temperature.htm");
    driver.manage().window().setSize(new Dimension(1053, 808));
    {
      WebElement element = driver.findElement(By.linkText("Message Forum"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("what")).click();
    driver.findElement(By.name("what")).sendKeys("40");
    {
      WebElement dropdown = driver.findElement(By.name("from"));
      dropdown.findElement(By.xpath("//option[. = 'degree Fahrenheit']")).click();
    }
    driver.findElement(By.cssSelector("td:nth-child(1) option:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.name("to"));
      dropdown.findElement(By.xpath("//option[. = 'degree Rankine']")).click();
    }
    driver.findElement(By.cssSelector("td:nth-child(2) option:nth-child(3)")).click();
    driver.findElement(By.name("Go")).click();
    
    driver.close();
  }
}